FROM nginx:1.10-alpine

#  default conf for proxy service
COPY ./development/nginx.conf /etc/nginx/nginx.conf

# NOT FOUND response
COPY ./notfound.html /var/www/html/notfound.html

# Proxy configurations
COPY ./includes/ /etc/nginx/includes/

#conf
COPY ./development/site-availables/ /etc/nginx/includes/site-availables/