version: "3.8"
services:
    proxy:
        build:
            context: ./
            dockerfile: ./development/dockerfile
        networks:
            - app
        ports:
            - "8080:8080"
            - "8082:8082"
            - "8083:8083"
            - "8084:8084"
            - "8085:8085"
            - "8086:8086"
            - "8088:8088"
networks:
    app:
        external: true
